# Generated by Django 5.0 on 2024-04-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_delivery_challan_igst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_challan_reference',
            name='reference_number',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
