# Generated by Django 5.0 on 2024-04-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_alter_delivery_challan_item_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_challan',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
